apiVersion: v1
kind: ServiceAccount
metadata:
  name: testkube
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testkube-reader
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: testkube-read-everything
subjects:
- kind: ServiceAccount
  name: testkube
  namespace: default # change this!
roleRef:
  kind: ClusterRole
  name: testkube-reader
  apiGroup: rbac.authorization.k8s.io