apiVersion: batch/v1
kind: Job
metadata: 
  name: "{{ .Name }}"
  namespace: "{{ .Namespace }}"
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: testkube
      containers:
        - name: "{{ .Name }}"
          image: "{{ .Image }}"