apiVersion: batch/v1
kind: Job
metadata: 
  name: "{{ .Name }}"
  namespace: "{{ .Namespace }}"
  annotations:
    kubernetes.twilio.com/service-name: "podinfo"
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: testkube
      containers:
        - name: "{{ .Name }}"
          image: "{{ .Image }}"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all