apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: testkube-api-server
  namespace: twilio-system-testkube
  labels:
    app.kubernetes.io/instance: testkube
    app.kubernetes.io/name: api-server
spec:
  namespaceSelector:
    matchNames:
    - twilio-system-testkube
  podMetricsEndpoints:
  - port: http
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: testkube
      app.kubernetes.io/name: api-server